[package]
name = "kcm-server"
edition.workspace = true
version.workspace = true
description = "HTTP server for KCM REST API"

[dependencies]
kcm-core = { path = "../kcm-core" }
kcm-runtime = { path = "../kcm-runtime" }
kcm-interface = { path = "../kcm-interface" }
kcm-security = { path = "../kcm-security" }
actix-web.workspace = true
tonic.workspace = true
prost.workspace = true
serde.workspace = true
serde_json.workspace = true
env_logger.workspace = true
log.workspace = true
tokio.workspace = true

[build-dependencies]
tonic-build.workspace = true

[[bin]]
name = "kcm-server"
path = "src/main.rs"

[[bin]]
name = "kcm-grpc"
path = "src/grpc_main.rs"

[lints]
workspace = true
