[package]
name = "kcm-storage"
edition.workspace = true
version.workspace = true
description = "Columnar storage engine for KCM"

[dependencies]
kcm-core = { path = "../kcm-core" }
log.workspace = true
parking_lot.workspace = true
zstd.workspace = true
lz4.workspace = true
blake3.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
