[package]
name = "kcm-distributed"
edition.workspace = true
version.workspace = true
description = "Distributed architecture for KCM"

[dependencies]
kcm-core = { path = "../kcm-core" }
kcm-security = { path = "../kcm-security" }
parking_lot.workspace = true
rayon.workspace = true

[lints]
workspace = true
