[package]
name = "kcm-core"
edition.workspace = true
version.workspace = true
description = "Core types and data structures for KCM"

[dependencies]
parking_lot.workspace = true
serde = { workspace = true, optional = true }

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true
static_assertions.workspace = true

[features]
default = []
serialization = ["serde"]

[lints]
workspace = true
